;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Sensors body]
Pos=16,118
Size=785,885
Collapsed=1

[Window][Sensors raw]
Pos=54,72
Size=711,48
Collapsed=0
DockId=0x00000001,0

[Window][Servo]
Pos=542,14
Size=1049,48
Collapsed=1
DockId=0x00000002,0

[Window][Power]
Pos=18,41
Size=513,660
Collapsed=1

[Window][Serial Connection]
Pos=16,10
Size=369,171
Collapsed=0

[Window][Orientation]
Pos=47,180
Size=886,392
Collapsed=1

[Window][Estimation inertial]
Pos=75,256
Size=1050,603
Collapsed=1

[Docking][Data]
DockNode  ID=0x00000001 Pos=54,72 Size=711,48 Selected=0x8147C072
DockNode  ID=0x00000002 Pos=542,14 Size=1049,48 Selected=0x4886578B

;;;<<<Layout_655921752_Default>>>;;;
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
